-- 010_update_users_auth.sql
TRUNCATE TABLE users CASCADE;

ALTER TABLE users ADD COLUMN IF NOT EXISTS username VARCHAR(255) UNIQUE;
UPDATE users SET username = 'temp_' || id WHERE username IS NULL;
ALTER TABLE users ALTER COLUMN username SET NOT NULL;

ALTER TABLE users ADD COLUMN IF NOT EXISTS is_admin BOOLEAN DEFAULT false;
ALTER TABLE users DROP COLUMN IF EXISTS email CASCADE;
