services:
  server:
    build: ./server
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file: .env
    environment:
      DATABASE_URL: postgres://larishome:larishome@host.docker.internal:5432/larishome
      JWT_SECRET: supersecretjwtkey_changeme
      PORT: 4000
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev

  client:
    build: ./client
    restart: unless-stopped
    depends_on:
      - server
    environment:
      VITE_API_URL: http://localhost:4000
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev -- --host
